server:
  port: 8080
  compression:
    # 默认不开启压缩，请配合nginx使用
    enabled: false

spring:
  application:
    name: lazyzzz-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  servlet:
    multipart:
      max-file-size: 10MB #最大文件上传上限

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
  type-enums-package: club.lazyzzz.web.model.enums

knife4j:
  production: true #线上环境请关闭开发文档

#lazyzzz:
  # 若要使用七牛云，请手动开始
  #qi-niu-property:
    #access-key: access-key #七牛云access-key
    #secret-key: secret-key #七牛云secret-key
    #bucket-name: bucket #七牛云access-key
    #domain: http://localhost # 七牛云绑定域名

logging:
  file:
    path: ${user.home}/lazyzzz/logs
