version: '3'
services:
  mysql:
    image: mysql:8
    container_name: blog-mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=123456 #请务必更改默认密码
      - MYSQL_DATABASE=blog
    ports:
    - "3306:3306"

  web:
    image: lazyzzz/lazyzzz-blog
    container_name: blog-web
    restart: always
    volumes:
      - ./lazyzzz:/root/lazyzzz
    environment:
      - MYSQL_ROOT_PASSWORD=123456 #务必保证与上文的MYSQL密码一致
      - JAVA_OPTS="-Xms256m -Xmx256m" #虚拟机参数，按需更改
    ports:
      - "8080:8080"
    depends_on:
      - mysql
